# Change these first
owner: joahn3 # Your GitHub organization or username, where this repository lives
repo: earthlink-uptime # The name of this repository
user-agent: joahn3

sites:
  - name: solarlink
    url: https://solarlink.ro
    icon: https://solarlink.ro/build/assets/solarlink_logo-7db92c46.svg
  - name: earthlink
    url: https://earthlink.ro
    icon: https://earthlink.ro/favico.png
  - name: GitLab xtelecom
    url: https://git.xtelecom.ro
    icon: https://git.xtelecom.ro/assets/logo-d36b5212042cebc89b96df4bf6ac24e43db316143e89926c0db839ff694d2de4.svg
  - name: earthlink status
    url: https://status.earthlink.ro
    icon: https://earthlink.ro/favico.png
  - name: earthlink status-backbone
    url: status-backbone.earthlink.ro
    icon: https://earthlink.ro/favico.png
  - name: xtelecom Admin
    url: https://admin.xtelecom.ro/login
    icon: 
  - name: RoNet
    url: https://ronet.xtelecom.ro/
    icon: https://ronet.xtelecom.ro/imagini/xtelecom.png
  - name: Tsty
    url: https://www.tsty.ro
    icon: https://www.tsty.ro/favicons/favicon.ico
  - name: Tsty ERP
    url: https://app.tsty.ro
    icon: https://app.tsty.ro/images/logo.svg
  - name: Laravel Enso
    url: https://laravel-enso.com
    icon: https://avatars.githubusercontent.com/u/26483909?s=200&v=4
  - name: Laravel Enso Docs
    url: https://docs.laravel-enso.com
    icon: https://avatars.githubusercontent.com/u/26483909?s=200&v=4
  - name: Rolcris
    url: https://rolcris.ro
    icon: https://www.rolcris.ro/favicons/favicon.ico
  - name: Rolcris ERP
    url: https://erp.rolcris.ro
    icon: https://www.rolcris.ro/favicons/favicon.ico
  - name: CRM Rolcris
    url: https://crm.rolcris.ro/login
    icon: https://crm.rolcris.ro/images/logo.svg
  - name: CEI Sales
    url: https://ceisales.com
    icon: https://ceisales.com/favicons/favicon.ico
  - name: CEI Sales App
    url: https://app.ceisales.com/login
    icon: https://app.ceisales.com/images/logo.svg
  - name: CEI Sales Wiki
    url: https://wiki.ceisales.com/login
    icon: https://wiki.ceisales.com/vendor/wiki/icon.png
  - name: KM Digital
    url: https://k-m.com
    icon: https://k-m.com/app/uploads/2016/05/logo.svg
  - name: Secom
    url: https://www.secom.ro
    icon: https://www.secom.ro/img/frontend/secom-logo.svg
  - name: BLT
    url: https://www.blt.ro
    icon: https://www.blt.ro/_res/media/media-generala/favicon-blt3.png
  - name: MIBA
    url: https://www.miba.ro
    icon: https://www.miba.ro/img/logo.png
  - name: MegaConstruct
    url: https://www.megaconstruct.ro
    __dangerous__insecure: true
    maxResponseTime: 20000
    icon: https://www.megaconstruct.ro/wp-content/uploads/2016/06/final-logo.jpg
  - name: TCC Iasi
    url: https://www.tcc-iasi.ro
    icon: https://www.tcc-iasi.ro/images/logo.png
  - name: Felix Telecom
    url: https://www.felixtelecom.ro
    icon: https://www.felixtelecom.ro/assets/img/svg/logo-intreg.svg
  - name: Paicu & Sons Consulting
    url: https://paicucons.ro
    icon: https://paicucons.ro/wp-content/themes/paicu/inc/assets/images/logo-dark.png
  - name: Amoobi
    url: https://www.amoobi.com
    icon: https://www.amoobi.com/files/design/logo_amoobi.png
  - name: GlobStar 1
    url: https://globstar.ro
    __dangerous__insecure: true
    maxResponseTime: 20000
    icon: https://globstar.ro/img/dor-bionic-logo-1574507922.jpg
  - name: Ted Electric EU
    url: https://www.tedelectric.eu
    icon: https://www.tedelectric.eu/lay/ted-top/ted_top_r1_c1.png
  - name: GP Batteries
    url: https://www.gpbatteries.ro
    icon: https://www.globstar.ro/img/dor-bionic-logo-1574507922.jpg
  - name: Globstar B2B 
    url: https://b2b.globstar.ro
    icon: https://globstar.ro/img/dor-bionic-logo-1574507922.jpg
  - name: Globstar Service UPS
    url: https://serviceups.globstar.ro
    icon: https://serviceups.globstar.ro/wp-content/uploads/2019/09/globstar-logo-service-ups-specializat.png
  

status-website:
  theme: light
  metaTags:
    - name: "robots"
      content: "noindex"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /earthlink-uptime
  name: earthlink > Your IT&C Partner
  logoUrl: https://earthlink.ro/favico.png
  favicon: https://earthlink.ro/favico.png
  introTitle: Uptime monitor and status page.
  introMessage: It uses **real-time** data from our [GitHub repository](https://github.com/joahn3/earthlink-uptime).
  navbar:

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
